### ISSUE TITLE
cssdb v2 project changes

### ISSUE THREAD

**Issue by jonathantneal** [jonathantneal/cssdb#18]
I would like to make two significant changes to cssdb to help users in the future.

---

First, I would like to change feature IDs.

The current IDs have been problematic because they try to follow specification anchors, but [some features aren’t always covered in a single section](https://github.com/jonathantneal/css-db/pull/17#issue-169837345), and because sections are inconsistently named, just like spec headings are inconsistently named. On the later point, I asked the CSSWG about their anchors, received feedback from some major spec contributors https://github.com/w3c/csswg-drafts/issues/2255, and a good summary would be:

> there is no pattern you can predict for any of the headings

Therefore, I would like the [new IDs](https://github.com/jonathantneal/css-db/blob/feature/2.0.0/cssdb.json) to **name the _feature_ and provide _context_**, which seems more sensible and consistent. For example:

| old id | new id |
|:--- |:--- |
| css-cascade-all-shorthand | all-property |
| css-fonts-propdef-font-variant | font-variant-property |
| selectors-any-link-pseudo | any-link-pseudo-class |
| css-color-modifying-colors | color-mod-function |
| selectors-dir-pseudo | dir-pseudo-class |
| selectors-attribute-case | case-insensitive-attributes |
| css-color-functional-notation | color-functional-notation |
| css-nesting | nesting-rules |

---

Second, I would like to rename the project in github from `css-db` to `cssdb` because that is its name on npm, and because it’s easier to type.

---

TODO:

- [ ] Update cssdb badges on all projects
- [ ] Update postcss-preset-env to use the new ids
- [ ] Anything else?

cc: @ai, @shrpne, @vkrol, @keithjgrant,

**Comment by ai** [comment]
I always like shorter names 👍
