### ISSUE TITLE
Add unprefixed gap property

### ISSUE THREAD

**Issue by evgeny-petukhov** [jonathantneal/cssdb#21]
More info here https://github.com/postcss/autoprefixer/issues/1021

It's would be good to add this feature to cssdb, then create a postcss plugin and add it to `postcss-preset-env`.

@jonathantneal what do you think?

**Comment by jonathantneal** [comment]
A PostCSS gap properties plugin has been published https://jonathantneal.github.io/postcss-gap-properties/

**Comment by jonathantneal** [comment]
Added in cssdb 2.1.0!

Available in [Edge 16](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cssgridlayout/)
Available in [Chrome 66](https://www.chromestatus.com/feature/4986266210795520)
Available in [Firefox 61](https://bugzilla.mozilla.org/show_bug.cgi?id=1398482)
Available in [Safari 11.2](https://bugs.webkit.org/show_bug.cgi?id=180290)

**Comment by evgeny-petukhov** [comment]
Thanks a lot!
