### ISSUE TITLE
Add CSS Environment Variables env()

### ISSUE THREAD

**Issue by jonathantneal** [jonathantneal/cssdb#22]
This was added yesterday:

https://drafts.csswg.org/css-env-1/

**Comment by jonathantneal** [comment]
PostCSS Plugin created https://jonathantneal.github.io/postcss-env-function/

**Comment by jonathantneal** [comment]
Added in cssdb 2.1.0!

**Comment by erwinvanlun** [comment]
Just thinking: I'd need a different set of variables for development, staging and production environment. This seems to be interesting. If combined with scss @import statement @import 'environment.scss' this could work, couldn't it?
